export enum Colors {
    primary = 'primary',
    primaryHover = 'primary-hover',
    secondary = 'secondary',
    secondaryHover = 'secondary-hover',
    danger = 'danger',
    dangerHover = "danger-hover",
    success = 'success',
    successHover = 'success-hover',
    disabled='disabled',
    orange = 'orange',
    orangeHover='orange-hover',
    dark = 'dark',
    red = 'red',
    gray = 'gray',
    light = 'light',
}
