export enum Colors {
    almond = 'almond',
    darkAlmond = 'dark-almond',
    blueCustom = 'blueCustom',
    danger = 'danger',
    dark = 'dark',
    gray = 'gray',
    light = 'light',
    lightGray = 'light-gray',
    warning = 'warning',
    primary = 'primary',
    secondary = 'secondary',
    success = 'success',
    white = 'white',
}
